name: CI - Auto Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches: [ main ]
    
  # Allows manual deployment if required
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual deployment..'
        required: false
        default: 'testing'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          usedocker: true
          #           HEALTHCHECK
          healthcheck: ${{secrets.HEROKU_APP_URL}}
          delay: 30
          rollbackonhealthcheckfailed: true
        env:
          HD_MONGO_URI: ${{secrets.ENV_MONGO_URI}}
          HD_API_KEY: ${{secrets.ENV_API_KEY}}
          HD_SECRET_KEY: ${{secrets.ENV_SECRET_KEY}}
